expensewebsite/expenses/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'expenses'

urlpatterns = [
    path('', views.index, name='expenses'),
    path('add_expense', views.add_expense, name='add_expense'),
    path('expense_edit/<int:id>', views.expense_edit, name='expense_edit'),
    path('expense_delete/<int:id>', views.expense_delete, name='expense_delete'),
    path('search-expenses', csrf_exempt(views.search_expenses),name="search_expenses"),
    path('export_csv' , csrf_exempt(views.export_csv),name="export_csv"),
    path('export_excel' , csrf_exempt(views.export_excel),name="export_excel"),
    path('export_pdf' , csrf_exempt(views.export_pdf),name="export_pdf"),
    path('expense_category_summary', views.expense_category_summary, name="expense_category_summary"),
    path('stats', views.stats_view,name="stats"),
]

expensewebsite/expensewebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('expenses/', include("expenses.urls")),
    path('preferences/', include("userpreferences.urls")),
    path('income/', include("userincome.urls")),
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
]

expensewebsite/userincome/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'income'

urlpatterns = [
    path('', views.index, name='income'),
    path('add_income', views.add_income, name='add_income'),
    path('income_edit/<int:id>', views.income_edit, name='income_edit'),
    path('income_delete/<int:id>', views.income_delete, name='income_delete'),
    path('search-income', csrf_exempt(views.search_income),name="search_income"),
]

expensewebsite/templates/partials/_messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-sm alert-{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

expensewebsite/templates/partials/_sidebar.html
{% load static %}
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'expenses:expenses' %}">
          <span data-feather="home"></span>
          Dashboard <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'expenses:expenses' %}">
          Expenses
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'income:income' %}">
          Income
        </a>
      </li>
    </ul>

    <h6
      class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted"
    >
      <span>Summary</span>
      <a
        class="d-flex align-items-center text-muted"
        href="#"
        aria-label="Add a new report"
      >
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'expenses:stats' %}">
          Expenses Summary
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Income Summary
        </a>
      </li>
    </ul>


    <h6
      class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted"
    >
      <span>Settings</span>
      <a
        class="d-flex align-items-center text-muted"
        href="#"
        aria-label="Add a new report"
      >
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
         <a class="nav-link" href="{% url 'preferences' %}">
          Currency Preferences
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Account
        </a>
      </li>
    </ul>

  </div>
</nav>